### PR TITLE
changes necessary to pull from Siavash's tagged version

### PR DESCRIPTION
**Pull request by sjanssen2**

### CODE REVIEW

**Comment by wasade** [comment]
The test failure looks real, are you observing the same failure locally?

**Comment by sjanssen2** [comment]
Yes, the same error is reproducible locally on barnacle.

**Comment by sjanssen2** [comment]
I think it is due to an update in skbio API. DNA.id does not work any longer, we need to use DNA.metadata['id']

**Comment by wasade** [comment]
Okay

**Comment by sjanssen2** [comment]
all covered in PR #7

**Pull request closed without merging**
